flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Icon.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"


name: sncapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  riverpod: ^2.5.1
  flutter_launcher_icons: ^0.13.1
  camera: ^0.10.6
  google_mlkit_face_detection: ^0.5.0
  flutter_bloc: ^8.1.1
  image_editor: ^1.3.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true